title: Ximaz Website
email: obvious.ly.dev@gmail.com
description: This website contains all my GitHub project to easily promote them.
# The subpath of the website
baseurl: "/"
# The base hostname and protocol
url: "https://ximaz.github.io"
twitter_username: _Ximaz
github_username: ximaz

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jykyll-feed

