title: "Ximaz"
email: "obvious.ly.dev@gmail.com"
description: "This website contains all my GitHub project to easily promote them."
baseurl: "/"                   # The subpath of the website
url: "https://ximaz.github.io" # The base hostname and protocol
twitter_username: "_Ximaz"
github_username: "Ximaz"

# Build settings
markdown: "kramdown"
theme: jekyll-theme-hacker
plugins:
  - jykyll-feed
